// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbmlsgtuuslwddgfnfqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJibWxzZ3R1dXNsd2RkZ2ZuZnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzAwODQsImV4cCI6MjA2NDEwNjA4NH0.Gb4txUm0XrQWnUVt-bTyaN5KQ8rFyFlh0AGOd-FcbEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);